# Generated by Django 3.1.1 on 2020-10-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcuName',
            fields=[
                ('ecuName', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VinNumber',
            fields=[
                ('vinNumber', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScomoID',
            fields=[
                ('scomoID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ecuName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotaUpdate.ecuname')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('FileName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('BrowsFile', models.FileField(upload_to='')),
                ('FileType', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('ScomoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotaUpdate.scomoid')),
            ],
        ),
    ]
