# Generated by Django 3.1.1 on 2020-10-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FotaUpdate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDetail',
            fields=[
                ('campaignName', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('CampaignType', models.CharField(max_length=300)),
                ('startdate', models.DateField()),
                ('endDate', models.DateField()),
                ('sourceVersion', models.CharField(max_length=100)),
                ('TargetVersion', models.CharField(max_length=100)),
                ('ecuNames', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotaUpdate.ecuname')),
                ('packageFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotaUpdate.contentfile')),
                ('scomoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotaUpdate.scomoid')),
                ('vinNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotaUpdate.vinnumber')),
            ],
        ),
    ]
