# Generated by Django 3.1.1 on 2020-10-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotaUpdate', '0003_dynamichmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndetail',
            name='ecuNames',
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='ecuNames',
            field=models.ManyToManyField(to='FotaUpdate.EcuName'),
        ),
        migrations.RemoveField(
            model_name='campaigndetail',
            name='vinNumber',
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='vinNumber',
            field=models.ManyToManyField(to='FotaUpdate.VinNumber'),
        ),
    ]
