# Generated by Django 3.1.1 on 2020-10-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotaUpdate', '0005_auto_20201019_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigndetail',
            name='fwversion',
            field=models.ManyToManyField(to='FotaUpdate.FwVersion'),
        ),
    ]
