# Generated by Django 3.1.1 on 2020-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FotaUpdate', '0006_campaigndetail_fwversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndetail',
            name='scomoID',
        ),
        migrations.AddField(
            model_name='campaigndetail',
            name='scomoID',
            field=models.ManyToManyField(to='FotaUpdate.ScomoID'),
        ),
    ]
