# Generated by Django 3.1.1 on 2020-11-06 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FotaUpdate', '0007_auto_20201019_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinnumber',
            name='vedFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
