# Generated by Django 3.1.1 on 2020-11-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FotaUpdate', '0008_vinnumber_vedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardedVin',
            fields=[
                ('discardedVin_id', models.AutoField(primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=300)),
                ('campaignName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FotaUpdate.campaigndetail')),
            ],
        ),
    ]
